

repos:
  - repo: https://gitlab.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python2.7
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest
        stages: [push]
        language: system
        pass_filenames: false